config/routes.rb
Rails.application.routes.draw do
  get "home/index"
  resource :session
  resources :passwords, param: :token
  resources :users, only: [:index]
  resources :egzams
  resources :questions


  get 'home/show', to: 'home#show', defaults: { format: 'pdf' }

  get 'import/lista'
  post 'import/import'



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  allow_unauthenticated_access only: %i[ index ]
  def index
    if authenticated?
      @session = Current.session

      if !Current.user.pobral

        for i in (1..3)
          egz=Egzam.new
          nrp = Question.where(gr: i).count
          nr = rand(nrp)+1
          egz.user_id = Current.user.id
          egz.question_id = nr+(i-1)*3
          egz.created_at = DateTime.now
          egz.updated_at = DateTime.now
          egz.save!
        end
        Current.user.pobral = true
        Current.user.save!
      end
      @zestaw = Egzam.where(user_id: Current.user.id).order(:question_id)
      #@user = current_user
    end
  end


  def show
    @zestaw = Egzam.where(user_id: Current.user.id).order(:question_id)
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Egzamin: #{Current.user.name} #{Current.user.surname}",
               page_size: 'A4',
               template: "home/show",
               layout: "pdf",
               orientation: "Portrait",
               lowquality: false,
               zoom: 1,
               dpi: 150,
               encoding: 'UTF-8'
      end


    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% if !authenticated? %>
<div class="hero bg-base-200 h-96">
  <div class="hero-content text-center">
    <div class="max-w-xl">
      <h1 class="text-5xl font-bold">Kolokwium zaliczeniowe</h1>
      <p class="py-6">
        programowanie w języku Python - semestr zimowy 2024/25
      </p>
        <%= link_to 'Logowanie', new_session_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>
<% end %>


<% if authenticated? %>

  <div class="card bg-grey-100 p-5 border border-gray-700">
    <div class="card-body">
      <div class="grid grid-cols-3 gap-4">
        <div class="col-span-2">
          <h1 class="text-4xl font-bold text-center">Kolokwium zaliczeniowe</h1>
          <h1 class="text-3xl font-bold text-center">programowanie w języku Python - semestr zimowy 2024/25</h1>
        </div>
        <div >
          <%= link_to "Pobierz PDF", home_show_path(@zestaw, format: :pdf), target: "_blank", class: "btn btn-primary" %>
        </div>
      </div>
    </div>


      <div class="card-body">

      <h5><b> Zestaw pytań dla <%= Current.user.name %> <%= Current.user.surname %> wylosowany <%= @zestaw.first.created_at.strftime("%d.%m.%Y o %H:%M") %></b></h5>
      <% i=1 %>
      <% @zestaw.each do |z| %>
          <p class="font-bold">Pytanie. <%= i %></p>
        <%= z.question.tekst %><br>
        <% i+=1 %>
      <% end %>
      </p>
      <p class="italic">
        W pytaniu 3 nazwy plików są jednocześnie linkami do ich pobrania!
        Wyniki należy zapisać do zadania na platformie Teams w czasie przewidzianym dla zadania.
        Należy zapisać pliki odpowiednich programów Pythona o nazwach wskazujących na numer pytania, którego dotyczą,
        do rozwiązań należy dołączyć pobrany plik pdf z treścią zadań. Proszę nie pakować rozwiązań (te pliki nie są duże).
      </p>
      <h6 class="font-bold text-red-500 italic">
        Proszę kontrolować czas! Po zamknięciu zadania w Teams rozwiązania nie będą przyjmowane!
      </h6>
    </div>
  </div>
<% end %>

app/views/home/show.pdf.erb
  <h1>Kolokwium z programowania w języku Python</h1>
  <h2>III rok informatyki IIT/PANS 2024</h2>

  <% if authenticated? %>


        <h3> <b> Zestaw pytań dla <%= Current.user.name %> <%= Current.user.surname %> wylosowany <%= @zestaw.first.created_at.strftime("%d.%m.%Y o %H:%M") %></b></h3>


        <% i=1 %>
        <% @zestaw.each do |z| %>
          <b>Pytanie. <%= i %></b>
          <%= z.question.tekst %><br>
          <% i+=1 %>
        <% end %>

        <i>
          W pytaniu 3 nazwy plików są jednocześnie linkami do ich pobrania!<br>
          Wyniki należy zapisać do zadania na platformie Teams w czasie przewidzianym dla zadania.
          Należy zapisać pliki odpowiednich programów Pythona o nazwach wskazujących na numer pytania, którego dotyczą,
          do rozwiązań należy dołączyc pobrany plik pdf z treścią zadań. Proszę nie pakować rozwiązań (te pliki nie są duże).
        </i><br>
        <b>
          Proszę kontrolować czas! Po zamknięciu zadania w Teams rozwiązania nie będą przyjmowane!
        </b>


  <% end %>