config/routes.rb
Rails.application.routes.draw do
  get "home/index"
  resource :session
  resources :passwords, param: :token
  resources :users, only: [:index]
  resources :egzams
  resources :questions


  get 'home/show', to: 'home#show', defaults: { format: 'pdf' }

  get 'import/lista'
  post 'import/import'



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
end

app/models/egzam.rb
class Egzam < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/controllers/egzams_controller.rb
class EgzamsController < ApplicationController
  before_action :set_egzam, only: %w[ show edit update destroy ]

  # GET /egzams
  # GET /egzams.json
  def index
    @egzams = Egzam.all
  end

  # GET /egzams/1
  # GET /egzams/1.json
  def show
  end

  # GET /egzams/new
  def new
    @egzam = Egzam.new
  end

  # GET /egzams/1/edit
  def edit
  end

  # POST /egzams
  # POST /egzams.json
  def create
    @egzam = Egzam.new(egzam_params)

    respond_to do |format|
      if @egzam.save
        format.html { redirect_to @egzam, notice: "Egzam was successfully created." }
        format.json { render :show, status: :created, location: @egzam }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @egzam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /egzams/1
  # PATCH/PUT /egzams/1.json
  def update
    respond_to do |format|
      if @egzam.update(egzam_params)
        format.html { redirect_to @egzam, notice: "Egzam was successfully updated." }
        format.json { render :show, status: :ok, location: @egzam }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @egzam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /egzams/1
  # DELETE /egzams/1.json
  def destroy
    @egzam.destroy
    respond_to do |format|
      format.html { redirect_to egzams_url, notice: "Egzam was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_egzam
      @egzam = Egzam.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def egzam_params
      params.require(:egzam).permit(:user_id, :question_id)
    end
end

app/views/egzams/_form.html.erb
<%= form_with(model: egzam) do |form| %>
  <% if egzam.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(egzam.errors.count, "error") %> prohibited this egzam from being saved:</h2>

      <ul>
        <% egzam.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :question_id %>
    <%= form.number_field :question_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/egzams/edit.html.erb
<h1>Editing Egzam</h1>

<%= render 'form', egzam: @egzam %>

<%= link_to 'Show', @egzam %> |
<%= link_to 'Back', egzams_path %>

app/views/egzams/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Egzams</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Question</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @egzams.each do |egzam| %>
      <tr>
        <td><%= egzam.user_id %></td>
        <td><%= egzam.question_id %></td>
        <td><%= link_to 'Show', egzam %></td>
        <td><%= link_to 'Edit', edit_egzam_path(egzam) %></td>
        <td><%= link_to 'Destroy', egzam, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Egzam', new_egzam_path %>

app/views/egzams/new.html.erb
<h1>New Egzam</h1>

<%= render 'form', egzam: @egzam %>

<%= link_to 'Back', egzams_path %>

app/views/egzams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @egzam.user_id %>
</p>

<p>
  <strong>Question:</strong>
  <%= @egzam.question_id %>
</p>

<%= link_to 'Edit', edit_egzam_path(@egzam) %> |
<%= link_to 'Back', egzams_path %>