config/routes.rb
Rails.application.routes.draw do
  get "home/index"
  resource :session
  resources :passwords, param: :token
  resources :users, only: [:index]
  resources :egzams
  resources :questions


  get 'home/show', to: 'home#show', defaults: { format: 'pdf' }

  get 'import/lista'
  post 'import/import'



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"
end

app/views/layouts/_footer.html.erb
<footer class="footer footer-center bg-primary text-white text-base-content p-2">
  <aside>
    <p class="text-[8px]">Copyright © 2024 - AI4WIT</p>
  </aside>
</footer>

app/views/layouts/_navbar.html.erb
<div class="navbar bg-primary text-white">
    <div class="navbar-start">

      <img src="<%= asset_path('logo.jpg') %>" alt="Logo" class="h-12 w-25">
    </div>
    <div class="navbar-center hidden lg:flex">
      <% if authenticated? %>
            Jesteś zalogowany jako: <%= Current.user.name %> <%= Current.user.surname %>
            <%= Time.now.strftime(" %H:%M:%S") %>
      <% else %>
            <p>Nie jesteś zalogowany</p>
      <% end %>
    </div>


    <div class="navbar-end">
      <% if authenticated? %>
        <% if Current.user.login == 'and' %>
            <span class="nav-link">
                <%= link_to 'Start', home_index_path, class: "btn btn-outline bg-white text-primary btn-sm" %>
            </span>
            <span class="nav-link">
                <%= link_to 'Lista', import_lista_path, class: "btn btn-outline bg-white text-primary btn-sm" %>
            </span>
            <span class="nav-link">
                <%= link_to 'Pytania', questions_path, class: "btn btn-outline bg-white text-primary btn-sm" %>
            </span>
          <% end %>

        <%= button_to 'Wyloguj', session_path, method: :delete, class: "btn btn-outline bg-white text-primary btn-sm" %>

      <% else %>
        <%= link_to 'Logowanie', new_session_path, class: "btn btn-outline bg-white text-primary btn-sm" %>
      <% end %>

    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "EGGv1.0" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto h-screen px-5 flex flex-col">
      <div>
        <%= render "layouts/navbar" %>
      </div>
      <div class="flex-grow">
        <%= yield %>
      </div>
      <div>
        <%= render "layouts/footer" %>
      </div>
    </main>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>PDF Layout</title>
  <%= wicked_pdf_stylesheet_link_tag "pdf" %>
</head>
<body>
<%= yield %>
</body>
</html>